server:
  port: 8000
  servlet:
    context-path: /clinica
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/clinica
    username: postgres
    password: root
  jpa:
    generate-ddl: true
    show-sql: false
